### ISSUE TITLE
pygame canvas and sprite

### ISSUE THREAD

**Issue by ServiceDog** [StudioGnocchi/butts#2]
`import pygame` and create a canvas/window of sufficient size, place an image at the center

**Comment by pyrifer** [comment]
import pygame
from pygame.locals import *

pygame.init()

#background setup
(width, height) = (500, 500)
background_color = (255,255,255)
background = pygame.display.set_mode((width,height))
background.fill(background_color)

#icon setup 50x94
player = pygame.image.load("orca.png").convert()
(x, y) = (width / 2 - 25, height / 2 - 47)
background.blit(player, (x, y))
pygame.display.flip()

running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

pygame.quit()

**Comment by ServiceDog** [comment]
Go ahead and close this issue after changing .txt to .py for canvas. 

LGTM
